name: Email Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  send_email_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'GitHub Action Run - ${{ github.ref_name }}'
          body: 'A new change was pushed to the repository. See the details: ${{ github.ref_name }} on ${{ github.repository }} by ${{ github.actor }}'
          to: 'your_email@example.com'
          from: 'your_email@example.com'